language: c

env:
  - LUA="lua5.1"
  - LUA="lua5.2"
  - LUA="$(find /usr -name luajit\*|grep bin|head -n 1)"

branches:
  only:
    - master

install:
  - sudo apt-get -qy install luajit lua5.1 lua5.2
  - find /usr -name luajit\*

script: "$LUA task.lua"

notifications:
  email:
    recipients:
      - travis@popcount.org
